lichess:
  api:
    username: ejaque74
    password: xxxxxxxx

# See javadocs in OpeningExplorerService class  
throttling:
  minTimeBetweenCalls: 1100

# See javadocs in OpeningExplorerService class  (TODO: delete minRankForRatingAvg)  
searchParams:
  playerColor: white
  startPositionFEN: rnbq1rk1/pp2ppbp/3p1np1/2p5/2PP4/2N2NP1/PP2PPBP/R1BQK2R w KQ - 0 7
  startPositionColor: white
  
  # Suggested: 8 half moves (each 2 half moves it multiplies by 5 the time, comparing in the QGA 6 vs 8 moves)
  maxDepthHalfMoves: 8    
  
  maxPopularityPctg: 0.1
  minRankForRatingAvg: 3
  minPercentileForRatingAvg: 70.0
  minProbabilityOfMove: 0.05
  
  # tried 50 when checking ratings 2200,2500
  minGamesToExploreOpponentMove: 30
  
  minGamesToChooseGoodMove: 10

  # tried 50 when checking ratings 2200,2500
  minGamesToChooseCandidateMove: 30
  
output:
  file:
    path: "C:/Users/eajaquep/Documents/marrujo-qga-pos0-r2500-8hm.xlsx"
    # "//wsl.localhost/Ubuntu/home/eajaquep/Documents/good-moves5.xlsx"
    
    
pgnAnnotator:
  processing:
    batchSize: 200    